create table if not exists Users (
    id serial primary key,
    name varchar(100) not null,
    email varchar(100) unique not null,
    created_at timestamp default current_timestamp
);

insert into Users (name, email) values
('John Doe', 'john.doe@example.com'),
('Jane Smith', 'jane.smith@example.com'),
('Alice Johnson', 'alice.johnson@example.com'),
('Bob Brown', 'bob.brown@example.com'),
('Charlie Davis', 'charlie.davis@example.com'),
('Diana Prince', 'diana.prince@example.com'),
('Ethan Hunt', 'ethan.hunt@example.com'),
('Fiona Gallagher', 'fiona.gallagher@example.com'),
('George Costanza', 'george.costanza@example.com'),
('Hannah Montana', 'hannah.montana@example.com'),
('Ian Malcolm', 'ian.malcolm@example.com'),
('Jack Sparrow', 'jack.sparrow@example.com'),
('Katherine Johnson', 'katherine.johnson@example.com'),
('Liam Neeson', 'liam.neeson@example.com'),
('Mia Wallace', 'mia.wallace@example.com'),
('Noah Centineo', 'noah.centineo@example.com'),
('Olivia Pope', 'olivia.pope@example.com'),
('Paul Atreides', 'paul.atreides@example.com'),
('Quinn Fabray', 'quinn.fabray@example.com'),
('Rachel Green', 'rachel.green@example.com'),
('Sam Winchester', 'sam.winchester@example.com'),
('Tina Belcher', 'tina.belcher@example.com'),
('Ursula K. Le Guin', 'ursula.k.le.guinn@example.com'),
('Victor Frankenstein', 'victor.frankenstein@example.com'),
('Winston Churchill', 'winston.churchill@example.com'),
('Xena Warrior Princess', 'xena.warrior.princess@example.com'),
('Yara Greyjoy', 'yara.greyjoy@example.com'),
('Zoe Barnes', 'zoe.barnes@example.com'),
('Aaron Burr', 'aaron.burr@example.com');